include ':cslibrary4a'
include ':epctagcoder'
include ':csl-rfid-android-sdk'
include ':cs710aquickstart'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
